version: "3.9"
services:
  baucua-app:
    build: .
    ports:
      - "3000:3000" # React Development Server
      - "9000:9000" # Backend server
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
      - HOST=0.0.0.0
    command: ["npm", "run", "dev"]
