# docker-compose.yml
version: "3.9"

services:
  baucua-app:
    build: .
    container_name: baucua-game
    restart: unless-stopped
    expose:
      - "9000"
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=9000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - baucua-network

  nginx:
    image: nginx:alpine
    container_name: baucua-nginx
    restart: unless-stopped
    ports:
      - "80:80"  # HTTP
      - "443:443"  # HTTPS (nếu bạn có SSL)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./ssl:/etc/nginx/ssl:ro  # Nếu bạn có SSL certificates
    depends_on:
      - baucua-app
    networks:
      - baucua-network

networks:
  baucua-network:
    driver: bridge

# nginx.conf
server {
    listen 80;
    server_name localhost;  # Thay thế bằng domain hoặc IP của bạn

    # Frontend
    location / {
        proxy_pass http://baucua-app:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Backend API
    location /api {
        proxy_pass http://baucua-app:9000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # WebSocket connections
    location /socket.io/ {
        proxy_pass http://baucua-app:9000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # WebSocket specific settings
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Timeout settings
        proxy_read_timeout 86400;  # Timeout for WebSocket connections
        proxy_send_timeout 86400;
    }
}