version: "3.9"

services:
  baucua-app:
    build: .
    container_name: baucua-game
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - PORT=9000
      - REACT_APP_SOCKET_URL=http://167.235.150.190:9000
      - HOST=0.0.0.0
      - WDS_SOCKET_PORT=0
    volumes:
      - .:/app
      - /app/node_modules
      - /app/baucua-client/node_modules